Repository Pretzel-11-12/dreamketcher-be, pull requests merged in 2024-12, with the labels that each got.

#20 웹툰 등록 기능 구현
  .DS_Store
  .gitignore
  build.gradle
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/WebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
  src/main/java/pretzel/dreamketcherbe/member/repository/MemberRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: enhancement

#21 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#30 웹툰 신작 목록 조회 기능 구현
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/WebtoonStatus.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#28 관심 웹툰 등록 기능 추가
  src/main/java/pretzel/dreamketcherbe/domain/member/controller/MemberController.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/FavoriteWebtoonResponse.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/InterestedWebtoonResponse.java
  src/main/java/pretzel/dreamketcherbe/domain/member/entity/InterestedWebtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/member/exception/MemberExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/InterestedWebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/exception/WebtoonExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#45 Auth 버그 픽스
  build.gradle
  src/main/java/pretzel/dreamketcherbe/common/config/CorsConfig.java
  src/main/java/pretzel/dreamketcherbe/common/entity/BaseTimeEntity.java
  src/main/java/pretzel/dreamketcherbe/domain/auth/controller/AuthController.java
  src/main/java/pretzel/dreamketcherbe/domain/auth/jwt/JwtExtractor.java
  src/main/java/pretzel/dreamketcherbe/domain/member/entity/Member.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
  src/main/resources/application-local.yml
Labels: bug

#55 에피소드 조회
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/EpisodeLike.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/EpisodeStar.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#64 백오피스 작품 및 회차 관리 기능
  src/main/java/pretzel/dreamketcherbe/domain/admin/controller/ManageEpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/controller/ManageWebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageEpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/UpdateWebtoonStatusReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ManagementEpisode.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ManagementWebtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/Reason.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ReasonContent.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/exception/AdminException.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/exception/AdminExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/repository/ManagementEpisodeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/repository/ManagementWebtoonRespository.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/repository/ReasonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageEpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageWebtoonService.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/EpisodeStatus.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/SerializationPeriod.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/WebtoonStatus.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/exception/WebtoonExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/AuthorRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/SerializationPeriodRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonGenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
Labels: enhancement

#56 검색 기능 구현
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/SearchedWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/exception/WebtoonExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#67 Feature/comment
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateCommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateCommentResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Comment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/exception/CommentException.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/exception/CommentExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/CommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: enhancement

#66 웹툰 목록 조회 기능 추가
  src/main/java/pretzel/dreamketcherbe/domain/admin/controller/ManageWebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ManagementEpisode.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ManagementWebtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageWebtoonService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/exception/WebtoonExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonGenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#72 랭킹 기능
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/WebtoonEpisodeListResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/controller/RankingController.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/RankingResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/WebtoonPopularityDataDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/service/RankingService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Like.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
Labels: enhancement

#78 랭킹 기능 구현
  src/main/java/pretzel/dreamketcherbe/domain/ranking/controller/RankingController.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/service/RankingService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
Labels: enhancement

#73 웹툰 복합 조회 기능 추가
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/exception/WebtoonExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonGenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#79 Feature/episode star
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeStarReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeStarResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/EpisodeStar.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/exception/EpisodeExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeStarRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#80 웹툰 조회 기능 수정
  .gitignore
  build.gradle
  src/main/java/pretzel/dreamketcherbe/common/config/QueryDslConfig.java
  src/main/java/pretzel/dreamketcherbe/common/dto/PageReqDto.java
  src/main/java/pretzel/dreamketcherbe/common/dto/PageResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/WebtoonStatus.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepositoryCustom.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepositoryCustomImpl.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement
