Repository Pretzel-11-12/dreamketcher-be, pull requests merged in 2025-02, with the labels that each got.

#159 웹툰 등록시 장르 추가
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/WebtoonGenreResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/WebtoonGenre.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/GenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#158 story, description 통합
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/MyWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/SearchedWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#157 논리삭제 수정 & 확장
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/CommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/NotRecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentNotRecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeLikeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeStarRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#160 승인 상태 추가
  src/main/java/pretzel/dreamketcherbe/batch/config/BatchSchedulerConfig.java
  src/main/java/pretzel/dreamketcherbe/batch/config/EpisodeBatchConfig.java
Labels: documentation

#169 Feature/episode batch
  src/main/java/pretzel/dreamketcherbe/batch/config/BatchSchedulerConfig.java
  src/main/java/pretzel/dreamketcherbe/batch/config/EpisodeBatchConfig.java
  src/main/resources/application.yml
Labels: bug

#165 이미지 삭제 기능 추가
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#166 이미지 삭제 기능 추가
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#170 에피소드 리스트 목록, 범위 검색 API 분리
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/WebtoonEpisodeListResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#171 Feature/comment
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CommentResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Comment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/exception/CommentExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: enhancement

#177 Feature/episode batch
  src/main/java/pretzel/dreamketcherbe/batch/config/BatchSchedulerConfig.java
Labels: bug

#176 feat: 검색 필드 story 추가
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/SearchedWebtoonResDto.java
Labels: enhancement

#178 저장방식 변경
  src/main/java/pretzel/dreamketcherbe/batch/config/EpisodeBatchConfig.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
Labels: bug
