Repository Pretzel-11-12/dreamketcher-be, pull requests merged in 2025-01, with the labels that each got.

#81 Feature/webtoon registration
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
Labels: enhancement

#85 랭킹 조회 기능에 QueryDsl 적용
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/RankingResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/WebtoonPopularityDataDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/repository/RankingRepositoryCustom.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/repository/RankingRepositoryCustomImpl.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/service/RankingService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/GenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
Labels: enhancement

#86 에피소드 좋아요
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageEpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageWebtoonService.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeLikeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/EpisodeLike.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeLikeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeScheduler.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#87 웹툰 목록 조회 리팩토링
  src/main/java/pretzel/dreamketcherbe/common/dto/PageReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/member/controller/MemberController.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/WorkResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/WebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepositoryCustomImpl.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#93 작품 승인 변경 기능 구현
  src/main/java/pretzel/dreamketcherbe/domain/admin/controller/ManageWebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/UpdateWebtoonApprovalReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/UpdateWebtoonStatusReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ApprovalStatus.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/entity/ReasonContent.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/exception/AdminExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/repository/ManagementWebtoonRepositoryCustom.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageWebtoonService.java
Labels: enhancement

#92 Feature/image
  .DS_Store
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Controller.java
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Service.java
  src/main/java/pretzel/dreamketcherbe/S3Utils/exception/S3Exception.java
  src/main/java/pretzel/dreamketcherbe/S3Utils/exception/S3ExceptionType.java
  src/main/java/pretzel/dreamketcherbe/common/config/S3Config.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/UpdateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/exception/EpisodeExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: enhancement

#94 Feature/episode
  .DS_Store
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/UpdateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/WebtoonEpisodeListResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/exception/EpisodeExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#96 랭킹 ResDto에 필드 추가
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/RankingResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/WebtoonPopularityDataDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/repository/RankingRepositoryCustomImpl.java
Labels: enhancement

#95 프로필 변경 로직 수정
  src/main/java/pretzel/dreamketcherbe/domain/auth/google/dto/GoogleUserInfo.java
  src/main/java/pretzel/dreamketcherbe/domain/member/controller/MemberController.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/SelfInfoResponse.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/UpdateProfileRequest.java
  src/main/java/pretzel/dreamketcherbe/domain/member/entity/Member.java
  src/main/java/pretzel/dreamketcherbe/domain/member/exception/MemberExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
Labels: enhancement

#97 에피소드 조회 반환 값 수정, 유효성 검사 형식 수정
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeStarReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/UpdateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
Labels: enhancement

#98 랭킹 조회 쿼리 수정
  src/main/java/pretzel/dreamketcherbe/domain/ranking/repository/RankingRepositoryCustomImpl.java
Labels: enhancement

#102 refactor: SerializationPeriod 엔티티 수정
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/SerializationPeriod.java
Labels: refactor

#104 dev-redirect-uri 수정
  src/main/resources/application-dev.yml
Labels: bug

#105 다중 이미지 저장 형식 수정
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Service.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/UpdateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: bug

#99 댓글 조회 기능 구현
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CommentResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Comment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/CommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: enhancement

#100 답글 조회 기능 구현
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: enhancement

#101 웹툰 검색 응답 수정
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeStarRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/SearchedWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonGenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#110 프로필 이미지 S3 추가
  src/main/java/pretzel/dreamketcherbe/domain/member/controller/MemberController.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/UpdateProfileRequest.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
Labels: enhancement

#111 프로필 이미지, 정보 통합
  src/main/java/pretzel/dreamketcherbe/domain/member/controller/MemberController.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
Labels: enhancement

#108 fix: webtoon_id 값 추가
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeStarReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/EpisodeStar.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: bug

#109 DTO 타입 변경
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/CreateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/UpdateEpisodeReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
Labels: bug

#117 유저 작품 조회
  src/main/java/pretzel/dreamketcherbe/domain/member/controller/MemberController.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepositoryCustomImpl.java
Labels: enhancement

#112 작품 관리 목록 수정
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageWebtoonService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/SerializationPeriodRepository.java
Labels: enhancement

#113 응답 값 설정
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#114 파라미터 순서 수정, 응답 수정
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: bug

#115 폴더 생성 경로 수정
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Service.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: refactor

#116 응답 수정
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
Labels: refactor

#118 Feature/comment
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Comment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#119 fix: webtoonId 값 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Comment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#120 답글 commentID 연결 수정
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateRecommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#121 내 작품 정보 조회
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/MyWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/exception/WebtoonExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#122 fix: memberid 누락 수정
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: bug

#123 작가 작품 조회 필드 변경 및 쿼리 수정
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/WorkResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepositoryCustomImpl.java
Labels: enhancement

#124 응답 데이터 추가
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/EpisodeResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/exception/EpisodeExceptionType.java
Labels: bug

#125 응답 데이터 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CommentResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentResDto.java
Labels: enhancement

#126 fix: webtoonId 값 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#127 Feature/re comment
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#128 댓글 데이터 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
Labels: bug

#129 엔티티 타입 변경
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateRecommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#130 Feature/re comment
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRepository.java
Labels: bug

#131 파라미터 값 수정
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#132 평균 별점 값 DB 업데이트
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#134 에피소드 조회 시 별점 계산 기능 추가
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#135 이미지 수정
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Service.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: bug

#136 refactor: 오타 수정
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentResDto.java
Labels: duplicate

#137 chore: 에러 문구 수정
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: duplicate

#143 이미지 삭제, 수정 파라미터 수정
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Controller.java
  src/main/java/pretzel/dreamketcherbe/S3Utils/S3Service.java
Labels: bug

#144 댓글 프로필 이미지 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CommentResDto.java
Labels: enhancement

#145 답글 프로필 이미지 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/RecommentResDto.java
Labels: enhancement

#146 조회 쿼리 추가
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRepository.java
Labels: bug

#106 댓글 추천/비추천
  build.gradle
  src/main/java/pretzel/dreamketcherbe/common/config/RedisConfig.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateRecommendationResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/NotRecommendationResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Comment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/NotRecommendation.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recommendation.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/exception/CommentExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/NotRecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
Labels: enhancement

#147 쿼리 수정
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/NotRecommendationRepository.java
Labels: bug

#148 파라미터 수정
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/NotRecommendation.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recommendation.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
Labels: bug

#107 답글 추천/비추천
  src/main/java/pretzel/dreamketcherbe/domain/comment/controller/CommentController.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateRecommentNotRecommendationResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/dto/CreateRecommentRecommendationResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/Recomment.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/RecommentNotRecommendation.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/entity/RecommentRecommendation.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/exception/CommentExceptionType.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/CommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentNotRecommendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRecomendationRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/repository/RecommentRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentScheduler.java
  src/main/java/pretzel/dreamketcherbe/domain/comment/service/CommentService.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeScheduler.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/CreateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/UpdateWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
Labels: enhancement

#149 스토리 변수 누락 수정
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/entity/Webtoon.java
Labels: bug

#151 웹툰에 장르 하나만 갖도록 수정
  src/main/java/pretzel/dreamketcherbe/domain/admin/dto/ManageWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/admin/service/ManageWebtoonService.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/WebtoonEpisodeListResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/WorkResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/RankingResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/dto/WebtoonPopularityDataDto.java
  src/main/java/pretzel/dreamketcherbe/domain/ranking/repository/RankingRepositoryCustomImpl.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/MyWebtoonResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/repository/WebtoonGenreRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/service/WebtoonService.java
Labels: enhancement

#152 기본 프로필 사진 변경
  build.gradle
  src/main/java/pretzel/dreamketcherbe/domain/auth/google/dto/GoogleUserInfo.java
  src/main/java/pretzel/dreamketcherbe/domain/auth/service/AuthService.java
  src/main/java/pretzel/dreamketcherbe/domain/member/dto/InterestedWebtoonResponse.java
  src/main/java/pretzel/dreamketcherbe/domain/member/entity/Member.java
  src/main/java/pretzel/dreamketcherbe/domain/member/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: enhancement

#153 SearchedWebtoonResDto 수정 및 검색어 유효성 검사추가
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/controller/WebtoonController.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/SearchWebtoonReqDto.java
  src/main/java/pretzel/dreamketcherbe/domain/webtoon/dto/SearchedWebtoonResDto.java
Labels: enhancement

#155 사용자 에피소드 좋아요, 별점 조회
  src/main/java/pretzel/dreamketcherbe/domain/episode/controller/EpisodeController.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/MemberEpisodeLikeAndStarResDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeLikeRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeStarRepository.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/service/EpisodeService.java
Labels: enhancement

#156 episode batch
  build.gradle
  src/main/java/pretzel/dreamketcherbe/DreamketcherbeApplication.java
  src/main/java/pretzel/dreamketcherbe/batch/config/BatchSchedulerConfig.java
  src/main/java/pretzel/dreamketcherbe/batch/config/EpisodeBatchConfig.java
  src/main/java/pretzel/dreamketcherbe/domain/auth/service/internal/AuthContext.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/dto/BatchEpisodeDto.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/entity/Episode.java
  src/main/java/pretzel/dreamketcherbe/domain/episode/repository/EpisodeRepository.java
  src/main/resources/application.yml
Labels: enhancement
